### ISSUE TITLE
BC break: zend-servicemanager 2.7.6 and zend-inputfilter 2.7.1 fatal error

### ISSUE THREAD

**Issue by pdrosos** [zendframework/zend-servicemanager#123]
Hello,

I have this fatal error in my code, when using zend-servicemanager 2.7.6 and zend-inputfilter 2.7.1:

```
Fatal error: Uncaught Error: Call to undefined method Zend\ServiceManager\ServiceManager::getServiceLocator() in vendor/zendframework/zend-inputfilter/src/InputFilterAbstractServiceFactory.php:74
Stack trace:
#0 vendor/zendframework/zend-servicemanager/src/ServiceManager.php(771): Zend\InputFilter\InputFilterAbstractServiceFactory->canCreateServiceWithName(Object(Zend\ServiceManager\ServiceManager), 'doctrine.connec...', 'doctrine.connec...')
#1 vendor/zendframework/zend-servicemanager/src/ServiceManager.php(716): Zend\ServiceManager\ServiceManager->canCreateFromAbstractFactory('doctrine.connec...', 'doctrine.connec...')
#2 vendor/dasprid/container-interop-doctrine/src/AbstractFactory.php(121): Zend\ServiceManager\ServiceManager->has('doctrine.connec...')
#3 vendor/dasprid/container-interop-doctrine/src/EntityManagerFactory.php(40): ContainerInteropDoctrine\AbstractFactory->retrieveDependency(Object(Zend in vendor/zendframework/zend-inputfilter/src/InputFilterAbstractServiceFactory.php on line 74
```

Is this a BC break in zend-servicemanager and could it be fixed? Thanks!

**Comment by weierophinney** [comment]
This is actually an issue with zend-inputfilter, not zend-servicemanager; I've created zendframework/zend-inputfilter#110 to address it.
